# Generated by Django 4.1.4 on 2022-12-26 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('daily_status', models.CharField(choices=[('Y', 'yes'), ('N', 'no')], max_length=1)),
            ],
        ),
    ]
